# -*- coding: utf-8 -*-
"""calculadora con 9 funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjjFVOBc1whvfHL3ZbeFRHmiqxndTnmE
"""

import math

def calculadora():
    print("Bienvenido a la Súper Calculadora")

    # Pedimos los números
    num1 = float(input("Ingresa el primer número: "))
    num2 = float(input("Ingresa el segundo número: "))

    # Mostramos las opciones
    print("\nSelecciona la operación que deseas realizar:")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicación")
    print("4. División")
    print("5. Coseno del primer número")
    print("6. Seno del primer número")
    print("7. Logaritmo base 10 del primer número")
    print("8. Elevar el primer número al segundo")
    print("9. Raíz cuadrada del primer número")

    opcion = input("\nIngresa el número de la operación: ")

    print("\nResultado:")
    if opcion == "1":
        print(f"Suma: {num1 + num2}")
    elif opcion == "2":
        print(f"Resta: {num1 - num2}")
    elif opcion == "3":
        print(f"Multiplicación: {num1 * num2}")
    elif opcion == "4":
        if num2 != 0:
            print(f"División: {num1 / num2}")
        else:
            print("Error: No se puede dividir por cero.")
    elif opcion == "5":
        print(f"Coseno: {math.cos(num1)}")
    elif opcion == "6":
        print(f"Seno: {math.sin(num1)}")
    elif opcion == "7":
        if num1 > 0:
            print(f"Logaritmo base 10: {math.log10(num1)}")
        else:
            print("Error: El logaritmo sólo se puede calcular para números positivos.")
    elif opcion == "8":
        print(f"{num1} elevado a {num2}: {math.pow(num1, num2)}")
    elif opcion == "9":
        if num2 >= 0:
            print(f"Raíz cuadrada de {num1}: {math.sqrt(num1)}")
        else:
            print("Error: No se puede calcular la raíz cuadrada de un número negativo.")
    else:
        print("Opción no válida.")

# Llamamos a la función
calculadora()

s = [ 1,2,3,4,5,6,7,8,9,10]
for i in s:
    print(i)