# -*- coding: utf-8 -*-
"""calculadora_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9YFzXLGPahBVgTdWH8iNSft1LpyKtk5

#calculadora sencilla
"""

print("bienbenido a tu primera calculadora")

  #se solicitan los numeros
  num1 = float(input("por favor ingrese el primer numero: "))
  num2 = float(input("por favor ingrese el segundo numero: "))

  #se muestran las opciones para hacer los calculos
  print("""Elige la operacion que se desea realizar:
  1. suma (+)
  2. resta (-)
  3. multiplicacion(*)
  4. divicion (/)""")

  opcion = input("ingresar la opcion deseada de 1 a 4: ")
  #definir el codigo para la operacion
  if opcion =="1":
    resultado = num1 + num2
    operacion ="+"
  elif opcion =="2":
   resultado = num1 - num2
   operacion ="-"
  elif opcion =="3":
   resultado = num1 * num2
   operacion ="*"
  elif opcion =="4":
    if num2 != 0:
      resultado = num1/num2
      operacion = "/"
    else:
      print("la divicion entre cero no esta definida.")
  else:
    print("opcion invalida")

  print(f"resultado:{num1}{operacion}{num2}={resultado}")