# -*- coding: utf-8 -*-
"""ciclo for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xtfb-td-gdA9jorMbHSNIau7QL592xyT
"""

#lista
lista_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

#tupla
tupla_1 = ("rojo", "cafe", "azul marino", "blanco", "negro", "celeste", "amarillo", "verde", "violeta", "rosado")

#conjunto
conjunto_1 = {100, 102, 100, 14, 12, 10, 10, 13, 521, 23}

#diccionario
diccionario_1 = {"color: diferencicion de un croma", "numero: elemento para contar", "casa: sitio para vivir", "perro: animal de compañía"}

#prueva para el ciclo "for" en lista
for numero in lista_1:
    print(numero)

#prueva para ciclo "for" en tuple
for color in tupla_1:
    print(color)

#prueva para ciclo "for" en conjunto
for numero in conjunto_1:
    print(numero)

#prueva para ciclo "for" en diccionario
for palabra in diccionario_1:
    print(palabra)