# -*- coding: utf-8 -*-
"""proyecto 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_rtKnG7IjVVRMauy-4hGz_IbLc6LhIE
"""

import pandas as pd
import math

# Listas para almacenar los datos
codigos = []
marcas = []
materiales = []
costos = []

# Lista de opciones de materiales
opciones_material = ['acetato', 'pasta', 'tr90', 'metal', 'titanio']

# Preguntar cuántos armazones se van a ingresar
num_armazones = int(input("¿Cuántos armazones vas a ingresar? "))

contador = 0

while contador < num_armazones:
    print(f"\nIngresando datos del armazón #{contador + 1}")

    codigo = input("Código del armazón: ")
    marca = input("Marca del armazón: ")

    # Mostrar menú de materiales
    print("Tipos de material:")
    for i, material in enumerate(opciones_material):
        print(f"{i + 1}. {material}")

    # Selección de material
    seleccion_valida = False
    while not seleccion_valida:
        opcion = int(input("Selecciona el número de material: "))
        if opcion >= 1 and opcion <= len(opciones_material):
            material = opciones_material[opcion - 1]
            seleccion_valida = True
        else:
            print("Opción inválida. Intenta de nuevo.")

    # Ingresar costo
    costo = float(input("Costo de compra: "))

    # Agregar datos a las listas
    codigos.append(codigo)
    marcas.append(marca)
    materiales.append(material)
    costos.append(costo)

    contador += 1
# crear el data_dict
data_dict = {
    'Código': codigos,
    'Marca': marcas,
    'Material': materiales,
    'Costo': costos,}
# Crear el DataFrame usando pandas
df = pd.DataFrame(data_dict)
suma_total = math.fsum(costos)
df.loc['suma total'] = [''] * (len(df.columns)- 1) + [suma_total]

# Mostrar la tabla
print("\nInventario de Armazones:")
display(df)

# Calcular suma de costos usando math.fsum
suma_total = math.fsum(costos)

print(f"\nLa suma total de los costos es: ${suma_total:.2f}")
df = pd.DataFrame(data_dict)
#print(df)
#call a variable
df