# -*- coding: utf-8 -*-
"""EDA_titanic.csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EcSYpvLQK6QHvh5Pq7Ev5SJ19IUt0uS
"""

import pandas as pd
import sklearn
import seaborn as sns
df_titanic = pd.read_csv('titanic.csv')
df_titanic

"""# Task
Add code to generate graphs for data exploration and visualization of survival distribution, survival by sex, survival by passenger class, survival by age, survival by fare, survival by number of siblings/spouses aboard, and survival by number of parents/children aboard to the existing Python code.

## Análisis exploratorio de datos (eda)

### Subtask:
Realizar un análisis exploratorio de los datos para entender la distribución de las variables y la relación entre ellas.

**Reasoning**:
The subtask requires performing exploratory data analysis on the `df_titanic` DataFrame. This involves displaying the first few rows, getting statistical summaries, checking data types and null values, and counting unique values. These steps can be combined into a single code block for efficiency.
"""

display(df_titanic.head())
display(df_titanic.describe())
display(df_titanic.info())
display(df_titanic.nunique())

"""## Visualización de la distribución de supervivencia

### Subtask:
Crear gráficas para visualizar la distribución de la columna 'Survived' (Supervivencia).

**Reasoning**:
Create a countplot to visualize the distribution of the 'Survived' column as requested.
"""

import matplotlib.pyplot as plt
sns.countplot(x='Survived', data=df_titanic)
plt.title('Distribution of Survival (0=Not Survived, 1=Survived)')
plt.xlabel('Survival Status')
plt.ylabel('Count')
plt.show()

"""## Visualización de la supervivencia por sexo

### Subtask:
Visualizar la tasa de supervivencia en función del sexo.

**Reasoning**:
Create a countplot to visualize the survival rate by sex as requested in the instructions.
"""

sns.countplot(x='Sex', hue='Survived', data=df_titanic)
plt.title('Survival Rate by Sex')
plt.xlabel('Sex')
plt.ylabel('Count')
plt.show()

"""## Visualización de la supervivencia por clase de pasajero

### Subtask:
Visualizar la tasa de supervivencia en función de la clase de pasajero ('Pclass').

**Reasoning**:
Create a countplot to visualize the survival rate by passenger class, set the title and axis labels, and display the plot.
"""

sns.countplot(x='Pclass', hue='Survived', data=df_titanic)
plt.title('Survival Rate by Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.show()

"""## Visualización de la supervivencia por edad

### Subtask:
Analizar la relación entre la edad y la supervivencia.

**Reasoning**:
Generate a density plot to visualize the distribution of 'Age' for both survived and non-survived passengers.
"""

sns.kdeplot(data=df_titanic, x='Age', hue='Survived', fill=True)
plt.title('Distribution of Age by Survival Status')
plt.xlabel('Age')
plt.ylabel('Density')
plt.show()

"""## Visualización de la supervivencia por tarifa

### Subtask:
Analizar la relación entre la tarifa pagada ('Fare') y la supervivencia.

**Reasoning**:
Create a density plot to visualize the distribution of 'Fare' for survived and not survived passengers, add title and labels to the plot.
"""

sns.kdeplot(data=df_titanic, x='Fare', hue='Survived', fill=True)
plt.title('Distribution of Fare by Survival Status')
plt.xlabel('Fare')
plt.ylabel('Density')
plt.show()

"""## Visualización de la supervivencia por número de hermanos/cónyuges a bordo

### Subtask:
Analizar la relación entre el número de hermanos/cónyuges a bordo y la supervivencia.

**Reasoning**:
Generate a countplot to visualize the relationship between the number of siblings/spouses aboard and survival as per the instructions.
"""

sns.countplot(x='Siblings/Spouses Aboard', hue='Survived', data=df_titanic)
plt.title('Survival Rate by Number of Siblings/Spouses Aboard')
plt.xlabel('Number of Siblings/Spouses Aboard')
plt.ylabel('Count')
plt.show()

"""## Visualización de la supervivencia por número de padres/hijos a bordo

### Subtask:
Analizar la relación entre el número de padres/hijos a bordo y la supervivencia.

**Reasoning**:
Create a countplot to visualize the relationship between the number of parents/children aboard and survival, then add title and labels to the plot, and finally display the plot.
"""

sns.countplot(x='Parents/Children Aboard', hue='Survived', data=df_titanic)
plt.title('Survival Rate by Number of Parents/Children Aboard')
plt.xlabel('Number of Parents/Children Aboard')
plt.ylabel('Count')
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   The initial exploratory data analysis revealed that the dataset contains 887 entries with no missing values across all columns, including 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', and 'Fare'.
*   Visualization of the overall survival distribution showed the counts of passengers who survived (1) and those who did not (0).
*   Analyzing survival by sex indicated a difference in survival rates between male and female passengers.
*   Visualizing survival by passenger class ('Pclass') demonstrated variations in survival rates across different passenger classes.
*   The density plot for age by survival status suggested differences in the age distribution between passengers who survived and those who did not.
*   The density plot for fare by survival status indicated differences in the distribution of fares paid by passengers who survived compared to those who did not.
*   Countplots for survival by the number of siblings/spouses aboard and by the number of parents/children aboard showed how the size of a passenger's family group on board related to their survival outcome.

### Insights or Next Steps

*   Further investigation into the specific differences in survival rates based on sex, passenger class, age, and fare could provide deeper insights into the factors influencing survival.
*   The visualizations of family size (siblings/spouses and parents/children) suggest that family composition might be a relevant factor in survival, warranting closer examination of specific family size categories.

"""