# -*- coding: utf-8 -*-
"""ejercicios de POO (programacion orientada a objetos)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeWhuiF068IBUUnwTje6HN-um8htoSK4

codigo 1 de programacion orientada a objetos
"""

class MiClase:
  #Atributos
  atributo1 = "Valor1"
  atributo2 = 0

  #Metodos
  def metodo1(self):
    print("Hola desde el metodo 1!")

  def metodo2(self, parametro):
    self.atributo2 = parametro
    print(f"El atributo2 se actualizo a: (self.atributo2)")

#creacion de objetos a partir de la clase
objeto1 = MiClase()
objeto2 = MiClase()

#acceso a atributos y llamada a metodos
print(objeto1.atributo1)      #salida valor1

objeto1.metodo1()             #salida ¡hola desde el metodo 1!

objeto2.metodo2(42) #salida el atributo2 se actualizo a: 42
print(objeto2.atributo2) #salida 42

"""codigo 2 de POO"""

class Coche:
  def __init__(self, marca, modelo, velocidad):
    self.marca = marca
    self.modelo = modelo
    self.velocidad = velocidad
  def acelerar(self, aumento):
    self.velocidad += aumento
    print(f"El coche{self.marca} {self.modelo} aceleró. Nueva velocidad: {self.velocidad} km/h")

#creacion de un objeto de tipo de coche
mi_coche = Coche("Toyota", "Land Cruiser", 0)

#acelerar el coche
mi_coche.acelerar(20)
mi_coche.acelerar(30)